# Generated by Django 2.1.2 on 2019-05-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviseMeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-vote']},
        ),
    ]
